name: Check & fix styling

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - name: Fix PHP code style
        uses: aglipanci/laravel-pint-action@2.6
        with:
          preset: laravel

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Fix Code Styling"
